version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin2022

  app:
    depends_on:
      - mysqldb
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysqldb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin2022

  mongo-express:
      depends_on:
        - mongodb
      image: mongo-express
      container_name: mongo-express
      restart: always
      ports:
        - 8083:8083
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=root
        - ME_CONFIG_MONGODB_ADMINPASSWORD=admin2022
        - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
    data: { }

#networks:
#    default:
#      name: db_network

#services: # adds 2 services: mysql and phpmyadmin to connect with
#  mysql:
#    image: mysql:latest # use latest version of mysql
#    container_name: mysql # add a name for the container
#    command: --default-authentication-plugin=mysql_native_password
#    restart: unless-stopped
#    environment: # add default values, see docs for more info.
#      MYSQL_USER: user
#      MYSQL_ROOT_PASSWORD: admin
#      MYSQL_PASSWORD: admin2022
#      MYSQL_DATABASE: pocdb # create this database on startup
#    volumes:
#      - my-db:/var/lib/mysql
#    ports:
#      - '3306:3306'
#
#  phpmyadmin:
#    container_name: phpmyadmin
#    image: phpmyadmin/phpmyadmin:latest
#    ports:
#      - "8082:8082"
#    environment:
#      MYSQL_ROOT_PASSWORD: admin #(Required) set the password for the root superuser account.
#      PMA_HOST: mysql   # define the address/hostname of the mysql server eg mysql container name.
#      PMA_USER: root # this is the root user to login on startup
#      PMA_PASSWORD: admin2022 # use the root password to login on startup.
#      # Create a new user on startup (optional)
#      # MYSQL_USER: newuser
#      # MYSQL_PASSWORD: mypassword
#
#volumes: # add persistent data even if container is removed.
#  my-db:
#
#networks:
#  default:
#    name: mysql_network